env:
  - CXX="g++-4.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js

node_js:
  - 8

deploy:
  provider: npm
  email: bobby.biran@medopad.com
  api_key:
    secure: gB7Tibi0cC0u2ysu75QR8ab+W4DKvFoZEkQRIi8BLgvoEi6nN/yFDrIaDhlDcK2udjaalfchkzzvEwa8+z5YNJkwp879TwG8Nz3M9ScxOYf9NVF2dB5i3NDxOQFQruJxmNidsIj0+QR7p/mvuL1vO5K4EH9Du+kL9/jbUUvF1OJhbylmbpoiNWX/KahBQnHpw0581J+n7eKTzEoJtNyR2hGyxm1SGTtilHacLq8Ue6/89qd8HUi2E1aNL4gXPyI56MPdvffMKVxM70Dp29AteeqJpJNXyju1EiDmgHf6noYmq4VocXF7LlUn4muNCojIgimhSF2ZCXDhNDeyajMA2rleWaDSMrHHig6GM/ytg1FYgH7sqosUL7DfnPn54QdLZTnfu+ZrVg/SvsZwzbfSsrtkmG/txg5gNy9KnEwBJkpb6xDVC5vgfmzF5+utpbh2+nDZxhHjTq5NKLSPxvLXCJ/nI6UTyvydl3O+rqcDR5rXRLUMrp/a4wRWRXpNtpgy152tRL4QbcD0Awu7/3UqzOF8WIaR+tGOuaoFDqPdmGS3FM8wy5vTtx8+IP6LSO4I3xfCp5yZqSlUlio6qDMRfdLy4vxsYJZ7VJNuN06EbAh2ZFSVkxV8aEh20KyxpS715mKqboCr9Iv7C9qi/AEhKqiXMBPRIuKzZNwt6n9eSME=
  on:
    tags: true
    repo: Medopad/babel-preset-medopad
